### ISSUE TITLE
Need support output changelog to html format

### ISSUE THREAD

**Issue by toancong** [toancong/clgt#21]
Need this feature to inform to our teams's members in easier reading than markdown.

**Comment by binhqd** [comment]
Hi @toancong , please check my PR if that help: https://github.com/toancong/clgt/pull/22

**Comment by toancong** [comment]
Great! Thanks. I'm going to merge your PR.

**Comment by toancong** [comment]
Ag. Could you open PR to `develop` branch instead of `master`. We are work on `develop` first.
